baseurl: /sam-web-design-standards 

# Markdown config
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
# highlighter: rouge

name: Draft SAM Web Design Standards

# gh-pages requires index in root
# source: docs

version: 0.1.1

exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- CONTRIBUTING.md
- ".sass-cache"
- ".ruby-version"
- vendor
- node_modules

permalink: pretty

repos:
- name: Draft SAM Web Design Standards
  description: Main repository for the Draft U.S. Web Design Standards
  url: https://github.com/joshbruce/sam-web-design-standards
# - name: Draft SAM Web Design Standards Assets
#   description: Draft SAM Web Design Standards visual design assets
#   url: https://github.com/jbrucegsa/sam-web-design-standards-assets

# google_analytics_ua: UA-48605964-33

# sass:
#   sass_dir: _scss
#  style: :compressed

# All pages are within the _docs folder
# this makes Jekyll through gh-pages understand that.
collections:
  docs:
    output: true
    permalink: /


